server:
  port: 8080  # container-internal port
  tomcat:
    accesslog:
      enabled: true
      # "combined" includes remote addr & user agent; outputs to /logs in container
      pattern: combined

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}
  jpa:
    hibernate:
      ddl-auto: validate  # rely on Flyway for schema; do not auto-create
    open-in-view: false
    properties:           # Force Hibernate JDBC to use IST for timestamp binding/display at the JDBC layer
      hibernate.jdbc.time_zone: Asia/Kolkata
  flyway:
    enabled: true         # run migrations on startup

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # expose only health & info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

logging:
  level:
    root: INFO
    org.springframework: INFO
    dev.harborwatch: INFO
