{
 "title": "HarborWatch — SRE Overview",
 "panels": [
  {
   "title": "App p50 latency (s)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{job=\"app\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "App p95 latency (s)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"app\"}[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "App error rate (%)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "100 * ( sum(rate(http_server_requests_seconds_count{status=~\"5..\",job=\"app\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=\"app\"}[5m])) )",
     "legendFormat": "5xx %"
    }
   ]
  },
  {
   "title": "Container CPU (cores, hw-app)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"hw-app\"}[1m])",
     "legendFormat": "hw-app"
    }
   ]
  },
  {
   "title": "Container Memory % (hw-app)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 * (container_memory_working_set_bytes{name=\"hw-app\"} / container_spec_memory_limit_bytes{name=\"hw-app\"})",
     "legendFormat": "% used"
    }
   ]
  },
  {
   "title": "Uptime (1=up, 0=down) — blackbox probe",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-http\",instance=\"http://app:8080/actuator/health\"}",
     "legendFormat": "probe_success"
    }
   ]
  },
  {
   "title": "Alertmanager",
   "type": "text",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "options": {
    "content": "<a href=\"http://localhost:9093\" target=\"_blank\">Open Alertmanager</a>"
   }
  }
 ]
}